wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683150427.977671
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.9.16
      5: 0.15.1
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
